### ISSUE TITLE
Air Quality Lit Review- Overall Narrative

### ISSUE THREAD

**Issue by jfmartinez4** [ciesin-geospatial/TOPSTSCHOOL-air-quality#6]
Repo for this task: https://github.com/ciesin-geospatial/TOPSTSCHOOL-air-quality 

Github io page: https://ciesin-geospatial.github.io/TOPSTSCHOOL-air-quality/

Create a new doc of deliverables for this task on this folder: https://drive.google.com/drive/u/0/folders/1ADJVcS1fpu-v-orasSwEkRA-iUpR-9Z7

Done: Rough draft narrative with citations in the google review doc. 

A source of research papers can be found here:https://www.zotero.org/groups/5638572/topstschool/collections/IC4J25VH

A video of subject matter experts can be hound here: https://youtu.be/ISUXEJJP4tU

Example of a finished Lit review: https://docs.google.com/document/d/1PGlu5fh-TV8svXI_h2J3CiCaXYds2uIV0Nuuqok_-EY/edit?usp=sharing

**Comment by jfmartinez4** [comment]
@dhru-repository I've added more details to this task. Please let me know if you'd like to meet this week.

**Comment by dhru-repository** [comment]
added "overall narrative - draft" document to  https://drive.google.com/drive/u/0/folders/1ADJVcS1fpu-v-orasSwEkRA-iUpR-9Z7

**Comment by jfmartinez4** [comment]
DHRUVIL UPDATED NARRATIVE LIT REVIEW: https://docs.google.com/document/d/11JvpeBy6AXXMWnt5jw6w2qGm_cGK2agIMx5bc4fKoyw/edit

**Comment by jfmartinez4** [comment]
Looking at feedback from Juan and Linda.

**Comment by dhru-repository** [comment]
@jfmartinez4 Hello, Juan: I have updated the document with new content. I also provided the list of reference at the bottom. Please let me know if the writing fits the overall narrative that you envisioned. I look forward to your feedback.

**Comment by jfmartinez4** [comment]
@dhru-repository thanks!! I've sent it to the team for feedback.

**Comment by jfmartinez4** [comment]
Linda approved of final draft.

**Comment by jfmartinez4** [comment]
@jfmartinez4 please review Dhruvil's lit review.

**Comment by jfmartinez4** [comment]
@dhru-repository the team was able to review. Please move forward and add any in-text citations you may have missed.

**Comment by jfmartinez4** [comment]
Completed narrative lit review
