### ISSUE TITLE
Quarto Styles in Quarto renders for xarray collapsing display

### ISSUE THREAD

**Issue by jfmartinez4** [ciesin-geospatial/TOPSTSCHOOL-air-quality#8]
Find out the settings to collapse xarray display in this page: https://ciesin-geospatial.github.io/TOPSTSCHOOL-air-quality/m202-svi-tri-icis-places.html

Done: find out which setting needs to be applied to the code chunk or to the page to collapse the xarray's results.

**Comment by joshbrinks** [comment]
We just want to auto collapse the array values. Ideally leave the rest visible on render.

We can see [here](https://tutorial.xarray.dev/fundamentals/01_datastructures.html) that the array values should show a few then "..." then the last few to keep that section manageable. For whatever reason it's showing way too many.

The key search terms here are "xarray html representation"

You might be able to fix this with a custom css injection that has that icon action collapsed. I think that's where I would have started, but I don't have hours to work on this particular issue.

**Comment by xames3** [comment]
- you need to do this when you import `xarray` for collapsing the views:
```python
import xarray as xr

xr.set_options(
    keep_attrs=True,
    display_expand_attrs=False,
    display_expand_coords=False,
    display_expand_data=False,
    display_expand_data_vars=False
)
```

- this will collapse the views when rendering and is up to the user to expand them when needed.

**Comment by jfmartinez4** [comment]
Thanks @xames3 !

@joshbrinks let me know if you have time to try this on the SVI lesson.

**Comment by joshbrinks** [comment]
Cool. This appears to be working and I pushed the change
